version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      # 外部端口 暴漏ip 打开放后墙
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.50:29092
      # 副本集
      KAFKA_NUM_PARTITIONS: 3
  kafka2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29093:29093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      # 外部端口 暴漏ip 打开放后墙
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.50:29093
      # 副本集
      KAFKA_NUM_PARTITIONS: 3
